import openai
import backoff
import time
from openai.error import RateLimitError, APIError, ServiceUnavailableError, APIConnectionError
from .openai_utils import OutOfQuotaException, AccessTerminatedException
from .openai_utils import num_tokens_from_string, model2max_context

support_models = ['gpt-3.5-turbo', 'gpt-3.5-turbo-0301', 'gpt-4', 'gpt-4-0314','gpt-4o','your_model','qwen3-32b']

class Agent:
    def __init__(self, model_name: str, name: str, temperature: float, api_key: str, sleep_time: float = 0) -> None:
        """Create an agent
        Args:
            model_name(str): model name
            name (str): name of this agent
            temperature (float): higher values make the output more random, while lower values make it more focused and deterministic
            sleep_time (float): sleep because of rate limits
        """
        self.model_name = model_name
        self.name = name
        self.temperature = temperature
        self.memory_lst = []
        self.api_key = api_key
        self.sleep_time = sleep_time
        self.meta_prompt = None
        self.enable_thinking = False

    @backoff.on_exception(backoff.expo, (RateLimitError, APIError, ServiceUnavailableError, APIConnectionError), max_tries=20)

    def query(self, messages: "list[dict]", max_tokens: int, api_key: str, temperature: float) -> str:
        """Make a query to OpenAI API with retry support"""
        time.sleep(self.sleep_time)

        if max_tokens <= 0:
            raise ValueError(f"Invalid max_tokens: {max_tokens}. Must be positive.")

        assert self.model_name in support_models, f"Not support {self.model_name}. Choices: {support_models}"

        openai.api_key = api_key

        try:
            response = openai.ChatCompletion.create(
                model=self.model_name,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                stream=True,
                enable_thinking=self.enable_thinking,
            )
            # gen = response['choices'][0]['message']['content']
            # return gen
            full_response = ""
            for chunk in response:
                if 'choices' in chunk and len(chunk['choices']) > 0:
                    delta = chunk['choices'][0]['delta']
                    content = delta.get('content', '')
                    full_response += content

            return full_response

        except openai.error.InvalidRequestError as e:
            if "quota exceeded" in str(e).lower():
                raise OutOfQuotaException(api_key)
            elif "access terminated" in str(e).lower():
                raise AccessTerminatedException(api_key)
            else:
                raise 

    def set_meta_prompt(self, meta_prompt: str):
        """Set the meta_prompt
        Args:
            meta_prompt (str): the meta prompt
        """
        self.meta_prompt = meta_prompt
        self.memory_lst.append({"role": "system", "content": f"{meta_prompt}"})

    def add_event(self, event: str):
        """Add an new event in the memory
        Args:
            event (str): string that describe the event.
        """
        self.memory_lst.append({"role": "user", "content": f"{event}"})

    def add_memory(self, memory: str):
        """Monologue in the memory
        Args:
            memory (str): string that generated by the model in the last round.
        """
        self.memory_lst.append({"role": "assistant", "content": f"{memory}"})
        print(f"----- {self.name} -----\n{memory}\n")

    def ask(self, temperature: float = None, api_key: str = ''):
        """Query for answer
        Args:
        """
        # query
        num_context_token = sum([num_tokens_from_string(m["content"], self.model_name) for m in self.memory_lst])
        max_token = model2max_context[self.model_name] - num_context_token
        return self.query(self.memory_lst, max_token, api_key=self.api_key, temperature=temperature if temperature else self.temperature)
    
    def ask_single_turn(self, event_prompt: str, meta_prompt: str = None) -> str:
        self.memory_lst = []

        system_prompt = meta_prompt if meta_prompt is not None else self.meta_prompt
        if system_prompt is not None:
            self.memory_lst.append({"role": "system", "content": system_prompt})

        self.memory_lst.append({"role": "user", "content": event_prompt})

        response = self.ask()

        return response
